version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app